spring.application.name=space-x-rockets-app

spring.datasource.url=jdbc:postgresql://localhost:5435/postgres # - указываем порт (проброшенный в докере порт, или порт на локальной машине).
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
